### ISSUE TITLE
Migrate e2e tests to latest hardrhat and ethers v6

### ISSUE THREAD

**Issue by Romsters** [matter-labs/anvil-zksync#491]
#### 📝 Description

Migrate the e2e tests to ethers v6, upgrade dependencies to latest.

#### 🤔 Rationale

Switch to using zksync-ethers and latest hardhat to avoid issues with new compiler versions and outdated dependencies.

**Comment by itegulov** [comment]
Closed by https://github.com/matter-labs/anvil-zksync/pull/489
